name: Secret Scan Comparison

on:
  push:
    branches: [ "main" ]

jobs:
  gitleaks:
    if: github.actor == github.repository_owner
    name: Gitleaks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: gitleaks/gitleaks-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_CONFIG: '.gitleaks.toml'
          GITLEAKS_COMMAND: 'dir'  # Scans all files on disk directly
          
  betterleaks:
    if: github.actor == github.repository_owner
    name: Betterleaks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: dortort/betterleaks-action@v0.1.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # Pass custom path for Betterleaks configuration here:
          config: '.betterleaks.toml'
